# Generated by Django 2.2.8 on 2020-07-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Testing description fdhbfiuwlbfgnjwvljnfvlwubgwuilbfkuybeskw\nm'),
            preserve_default=False,
        ),
    ]
