# Generated by Django 2.2.8 on 2020-07-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200702_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.URLField(default='https://cdn.shopify.com/s/files/1/1501/4310/products/HoodieNewHaley_2048x.jpg?v=1590594693'),
        ),
    ]
