# Generated by Django 2.2.8 on 2020-07-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='label_name',
            field=models.CharField(blank=True, choices=[('N', 'NEW'), ('H', 'HOT'), ('F', 'FREE SHIPPING'), ('S', 'ON SALE')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('B', 'Bottom'), ('SW', 'Sport wear'), ('OW', 'Outerwear')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1, null=True),
        ),
    ]
