# Generated by Django 2.2.8 on 2020-07-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200705_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isBestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('W', 'warning'), ('D', 'danger')], max_length=1, null=True),
        ),
    ]
