# Generated by Django 2.2.8 on 2020-07-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200705_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('B', 'Bottom'), ('SW', 'Sport wear'), ('OW', 'Outerwear'), ('A', 'Accessories')], max_length=2),
        ),
    ]
