# Generated by Django 2.2.8 on 2020-07-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200705_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label_name',
            field=models.CharField(blank=True, choices=[('N', 'NEW'), ('H', 'HOT'), ('F', 'FREE SHIPPING')], max_length=1, null=True),
        ),
    ]
